### ISSUE TITLE
Figure out how to play nicely with ServiceWorkers.

### ISSUE THREAD

**Issue by stereobooster** [errorception/snapshotify#2]
By default CRA uses `index.html` as fallback 

```js
navigateFallback: publicUrl + '/index.html',
```

you need to change this to unprerendered version of index.html (typically `200.html`).

I do not know any other caveats here. Let me know if you find something else.

**Comment by rakeshpai** [comment]
Thanks! I simply haven't gotten around to looking at this yet, but I'll make sure I keep this in mind. Thanks again! Will let you know if I face any gotchas.

**Comment by stereobooster** [comment]
I will close this for now
